= Asciidoc 으로 시작하는 책쓰기용 템플릿
honeymon, <ihoneymon@gmail.com>
v0.0.1, 2018-02-26

****
아스키독(Asciidoc)을 기반으로 책을 쓸 수 있다는 일념으로 만든 템플릿 프로젝트

[NOTE]
====
실제로는 link:https://asciidoctor.org/[Asciidoctor]를 기반으로 하고 있다고 봐야함.
====
****

== 조기 설치방법 (최신 환경 기준)
이 프로젝트는 최신 **Asciidoctor 2.x** 환경에서 정상 작동하도록 업데이트되었습니다. macOS 기준, 아래 순서대로 실행하여 환경을 구축하세요.

1. **최신 Ruby 설치 (Homebrew 이용)**
[source,console]
----
$ brew install ruby
----

2. **환경 변수 설정**
설치된 Ruby를 우선 사용하도록 셸 설정 파일(`.zshrc` 등)에 아래 내용을 추가하세요. (현재 세션에서 바로 적용하려면 터미널에 복사-붙여넣기 하세요.)
[source,console]
----
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export GEM_HOME=$HOME/.gem/ruby/4.0.0
export PATH="$GEM_HOME/bin:$PATH"
----

3. **필수 라이브러리(Gems) 설치**
[source,console]
----
$ gem install rake asciidoctor asciidoctor-pdf asciidoctor-epub3 asciidoctor-diagram rouge
----

4. **한글 폰트 및 빌드 확인**
한글 PDF 생성을 위해 나눔고딕 폰트(`fonts/`)와 테마(`pdf-theme.yml`)가 준비되어 있습니다. 아래 명령으로 빌드하세요.
[source,console]
----
$ rake book:build
----

== 문서생성을 위한 사전요구사항
* 루비RUBY 설치 (v3.x 이상 권장)
* link:https://rubygems.org/[Ruby Gems] 설치
* link:http://bundler.io/[bundler(http://bundler.io/)] 설치
* link:https://pandoc.org/installing.html[Pandoc 설치]

== 책쓰기 프로젝트 시작
[source,console]
----
$ git clone git@github.com:ihoneymon/asciidoc-book-template.git
$ cd asciidoctor-book-template
$ git remote remove origin
$ rm -rf .git
$ bundle install // <1>
$ ./build.sh    // <2>
----
<1> ``Gemfile``을 읽어 ``Rakefile``을 실행하는데 필요한 의존성 라이브러리를 설치한다.
<2> ``build.sh``를 실행하면 ``publication`` 디렉토리리가 생성되고 그 안에 ``html``, ``docx``와 ``pdf`` 파일이 생성된다.

[NOTE]
====
생성되는 파일명을 변경하고 싶은 경우 ``build.sh``를 열어 ``publication`` 을 자신이 원하는 이름으로 변경하면 된다.

[source,console]
----
#!/usr/bin/env zsh
bundle exec rake "book:build[publication]"
----
====

[IMPORTANT]
====
빌드를 실행하면 ``asciidoctor-pdf-cjk-kai_gen_gothic``를 다운로드(하는 척) 하지만 실제로는 다운로드가 일어나지 않는다. asciidoctor-pdf 한글을 랜더링 하기 위해 한글폰트를 필요로 한다. 그 때는
link:https://www.dropbox.com/s/wn68fkdt93kkkw6/asciidoctor-pdf-font.tar?dl=0[]를 내려받고 ``gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1/data/fonts/`` 위치에 풀어넣으면 된다.

``asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1`` 폰트를 내려받을 수 없게 되어 있다. 
====

== 기타
궁금한 것이 있을 경우에는 [red]#커피 한 잔**이상**# 사주시면 **친절하게** 응해드립니다.

=== 코드영역에서 위치변환자(Placeholder)를 사용할 때
아스키독에서는 대체(substitutions) 라는 표현을 쓴다. 그래서 약자(``subs``)를 사용한다.

[source]
----
    :version: 1.5.6.1

    [source,xml,subs="verbatim,attributes"]
    ----
    <dependency>
      <groupId>org.asciidoctor</groupId>
      <artifactId>asciidoctor-java-integration</artifactId>
      <version>{version}</version>
    </dependency>
    ----
----

== 참고사항
* link:http://www.methods.co.nz/asciidoc/userguide.html[Asciidoc User Guide]
* link:https://asciidoctor.org/[Asciidoctor]
* link:https://rubygems.org/[Ruby Gems]
