= Asciidoc 으로 시작하는 책쓰기용 템플릿
honeymon, <ihoneymon@gmail.com>
v0.1.0, 2026-03-25

****
아스키독(Asciidoc)을 기반으로 책을 쓸 수 있다는 일념으로 만든 템플릿 프로젝트

[NOTE]
====
실제로는 link:https://asciidoctor.org/[Asciidoctor]를 기반으로 하고 있다고 봐야함.
====
****

== 사전 요구사항

* link:https://github.com/rbenv/rbenv[rbenv] — Ruby 버전 관리
* Ruby {ruby-version} 이상 (`.ruby-version` 파일에 명시)
* link:https://bundler.io/[Bundler] — Gem 의존성 관리
* link:https://pandoc.org/installing.html[Pandoc] — DOCX 변환 (선택사항)

== 환경 구성

=== 1. rbenv 설치 및 초기화

[source,console]
----
$ brew install rbenv ruby-build
$ echo 'eval "$(rbenv init -)"' >> ~/.zshrc
$ source ~/.zshrc
----

=== 2. Ruby 설치

[source,console]
----
$ rbenv install $(cat .ruby-version)
$ rbenv local $(cat .ruby-version)
----

=== 3. Bundler 및 의존성 설치

[source,console]
----
$ gem install bundler
$ bundle install
----

== 책쓰기 프로젝트 시작

[source,console]
----
$ git clone git@github.com:ihoneymon/asciidoc-book-template.git
$ cd asciidoc-book-template
$ git remote remove origin  # <1>
$ rm -rf .git               # <2>
$ git init && git add -A && git commit -m "Initial commit"
$ bundle install
$ ./build.sh
----
<1> 원본 저장소와의 연결을 끊는다.
<2> git 이력을 초기화하여 새 프로젝트로 시작한다.

빌드가 완료되면 `publication/` 디렉터리에 다음 파일이 생성된다.

[cols="1,3"]
|===
|파일 |설명

|`publication.html` | 웹 브라우저에서 확인 가능한 HTML
|`publication.docx` | Microsoft Word 문서 (pandoc 필요)
|`publication.pdf`  | 한글 폰트(NanumGothic)가 적용된 PDF
|`publication.epub` | 전자책 리더용 EPUB3
|===

[NOTE]
====
출력 파일명을 변경하려면 `build.sh` 의 `publication` 부분을 원하는 이름으로 수정한다.

[source,zsh]
----
bundle exec rake "book:build[my-book-name]"
----
====

== 한글 PDF

한글 PDF 생성을 위해 NanumGothic 폰트와 PDF 테마가 포함되어 있다.

* 폰트: `fonts/NanumGothic-Regular.ttf`, `fonts/NanumGothic-Bold.ttf`
* 테마: `pdf-theme.yml`

별도의 폰트 설치 없이 바로 빌드 가능하다.

== 기타

궁금한 것이 있을 경우에는 [red]#커피 한 잔**이상**# 사주시면 **친절하게** 응해드립니다.

=== 코드 영역에서 위치변환자(Placeholder) 사용

아스키독에서는 대체(substitutions)라는 표현을 쓰며 약자(`subs`)를 사용한다.

[source]
----
:version: 1.5.6.1

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.asciidoctor</groupId>
  <artifactId>asciidoctor-java-integration</artifactId>
  <version>{version}</version>
</dependency>
----
----

== 참고

* link:https://asciidoctor.org/[Asciidoctor]
* link:https://docs.asciidoctor.org/asciidoc/latest/[Asciidoc 문법 가이드]
* link:https://docs.asciidoctor.org/pdf-converter/latest/[Asciidoctor PDF]
* link:https://docs.asciidoctor.org/epub3-converter/latest/[Asciidoctor EPUB3]
* link:https://rubygems.org/[Ruby Gems]
